version: 4.0.{build}

image: Visual Studio 2019 Preview

pull_requests:
  do_not_increment_build_number: true

shallow_clone: true
clone_folder: C:\Projects\Victoria

only_commits:
  message: /Build/

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

before_build:
- cmd: dotnet restore

build:
  parallel: true
  verbosity: minimal

artifacts:
- path: '**\*.nupkg'
  name: Victoria

deploy:
- provider: NuGet
  api_key:
    secure: 2ERjvGaKjBby9aE8IHGo0uBHqXuosD3em2isgwubNPD9Zwt1q+y1WOopXW2dmH6j

on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/Yucked/Krypts/master/VeyorHook.ps1 -o VeyorHook.ps1
  - ps: ./VeyorHook.ps1 success $env:WEBHOOK_URL

on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/Yucked/Krypts/master/VeyorHook.ps1 -o VeyorHook.ps1
  - ps: ./VeyorHook.ps1 failure $env:WEBHOOK_URL
